# Colors (Onedark) Isabel Rice
colors:
  primary:
    background: '#eff1f5'
    foreground: '#4c4f69'

  normal:
    black:   '#5c6370'
    red:     '#d20f39'
    green:   '#40a02b'
    yellow:  '#df8e1d'
    blue:    '#1e66f5'
    magenta: '#8839ef'
    cyan:    '#209fb5'
    white:   '#eff1f5'

  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#e5c07b'
    blue:    '#61afef'
    magenta: '#8677cf'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  cursor:
    cursor: '#4c4f69'
    text:	'#4c4f69'
